### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by schweden1997** [OrJDev/solid-auth#1]
First of all great job with all the stuff you're developing for Solid.

A couple of days ago I basically started the same project by porting Remix Auth. As someone fairly new to the Solid world I'm happy that you created this. How do you imagine this going forward. Should we create new providers as separate packages or should they be part of this package? Maybe scoped packages for providers?

I am more than happy to contribute.

Cheers

**Comment by OrJDev** [comment]
First of all apologies for that I didn't know someone is already working on auth for solid,

But yes I do want it to be monorepoish and keep things separated like you did, its not urgent as everything is working fine but yes.

**Comment by OrJDev** [comment]
Apologies for that I didn't know someone is already working on auth for solid,

But yes I do want it to be monorepoish and keep things separated like you did.

For instance i think that we should have another package called ```@solidjs-auth/socials``` which will contain all of the oauth2 providers (discord, github etc) 
and since I had to port remix oauth2 to get it to work i think we should also have the oauth separated like remix auth did:

```@solidjs-auth/oauth``` and ```@solidjs-auth/core```

Form provider is also important idk how did i miss that, will do it and publish also under:

```@solidjs-auth/form```

meaning that providers should be seperated from the core.

 cool thing about this is you can actually redirect the user to login / logout from the client (using the createSolidAuthClient and handling the request with createSolidAuthHandler - remix auth doesn't have that)
Another thing I'm working on is the createSession hook, which can be used in the client side and will be updated onMount and whenever the login/logout is called.

If you are able to port this into a monorepo, feel free to contribute (:
